apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: gke-cicd-pipeline # Make sure this matches your Delivery Pipeline name
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./kubernetes/*
deploy:
  kubectl: {}
  logs:
    prefix: container

# ADD THIS SECTION:
profiles:
  - name: dev
  - name: prod